@extends('admin.layouts.app')
@section('title', 'تنظیمات فوتر')
@section('content')
@php
    $socialPlatforms = config('social_platforms', []);
    $footerSocials = collect(old('footer_social_links_items', $settings->get('footer.footer_social_links', [])))->map(function ($item, $key) {
        return is_array($item) ? $item : ['title' => $key, 'url' => $item, 'icon' => '', 'platform' => 'custom'];
    })->values();
@endphp
<div class="admin-page-toolbar"><div><p class="admin-eyebrow">تنظیمات</p><h2>تنظیمات فوتر</h2></div></div>
<form class="admin-panel-card admin-form" action="{{ route('admin.footer_settings.update') }}" method="POST" enctype="multipart/form-data">@csrf @method('PUT')
<div class="row g-3">
<div class="col-md-6"><label class="form-label">لوگوی فوتر</label><input class="form-control" type="file" name="footer_logo" accept="image/*">@if($settings->get('footer.footer_logo'))<small><a href="{{ Storage::url($settings->get('footer.footer_logo')) }}" target="_blank">مشاهده فعلی</a></small>@endif</div>
<div class="col-md-6"><label class="form-label">متن کپی‌رایت</label><input class="form-control" name="copyright_text" value="{{ old('copyright_text', $settings->get('footer.copyright_text', 'تمام حقوق مادی و معنوی این وبسایت متعلق به اتاق اصناف مرکز استان گلستان می‌باشد')) }}"></div>
<div class="col-12"><label class="form-label">توضیحات فوتر</label><textarea class="form-control js-rich-editor" name="footer_description" rows="4">{{ old('footer_description', $settings->get('footer.footer_description')) }}</textarea></div>
<div class="col-12"><label class="form-label">ستون‌های فوتر (JSON)</label><textarea class="form-control" name="footer_columns" rows="8" dir="ltr">{{ old('footer_columns', json_encode($settings->get('footer.footer_columns', []), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)) }}</textarea><small class="text-muted">مثال: [{"title":"دسترسی سریع","links":[{"title":"خانه","url":"/"}]}]</small></div>
<div class="col-12"><label class="form-label">اطلاعات تماس فوتر (JSON)</label><textarea class="form-control" name="footer_contact_info" rows="5" dir="ltr">{{ old('footer_contact_info', json_encode($settings->get('footer.footer_contact_info', []), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)) }}</textarea></div>
<div class="col-12"><label class="form-label">شبکه‌های اجتماعی فوتر</label><div data-social-list="footer_social_links_items" data-platforms='@json($socialPlatforms)' data-next-index="{{ $footerSocials->count() }}"><div data-rows>@foreach($footerSocials as $index => $social)<div class="row g-2 align-items-end mb-2" data-row><div class="col-md-2"><label class="form-label">شبکه</label><select class="form-control" name="footer_social_links_items[{{ $index }}][platform]">@foreach($socialPlatforms as $value => $platform)<option value="{{ $value }}" @selected(($social['platform'] ?? 'custom') === $value)>{{ $platform['icon'] }} {{ $platform['title'] }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">عنوان</label><input class="form-control" name="footer_social_links_items[{{ $index }}][title]" placeholder="عنوان" value="{{ $social['title'] ?? '' }}"></div><div class="col-md-4"><label class="form-label">لینک</label><input class="form-control" name="footer_social_links_items[{{ $index }}][url]" placeholder="لینک" dir="ltr" value="{{ $social['url'] ?? '' }}"></div><div class="col-md-2"><label class="form-label">آیکن</label><input class="form-control" name="footer_social_links_items[{{ $index }}][icon]" placeholder="آیکن" value="{{ $social['icon'] ?? '' }}"></div><div class="col-md-2"><button class="btn btn-outline-danger" type="button" data-remove-row>حذف</button></div></div>@endforeach</div><button class="btn btn-outline-primary" type="button" data-add-social>افزودن شبکه اجتماعی</button></div></div>
</div><div class="mt-3"><button class="admin-primary-btn">ذخیره تنظیمات فوتر</button></div></form>
@push('scripts')<script>document.addEventListener('click',function(e){const add=e.target.closest('[data-add-social]');if(add){const list=add.closest('[data-social-list]'),rows=list.querySelector('[data-rows]'),name=list.dataset.socialList,index=Number(list.dataset.nextIndex||0),platforms=JSON.parse(list.dataset.platforms||'{}');list.dataset.nextIndex=index+1;const options=Object.entries(platforms).map(([value,item])=>`<option value="${value}">${item.icon||''} ${item.title||value}</option>`).join('');rows.insertAdjacentHTML('beforeend',`<div class="row g-2 align-items-end mb-2" data-row><div class="col-md-2"><label class="form-label">شبکه</label><select class="form-control" name="${name}[${index}][platform]">${options}</select></div><div class="col-md-2"><label class="form-label">عنوان</label><input class="form-control" name="${name}[${index}][title]" placeholder="عنوان"></div><div class="col-md-4"><label class="form-label">لینک</label><input class="form-control" name="${name}[${index}][url]" placeholder="لینک" dir="ltr"></div><div class="col-md-2"><label class="form-label">آیکن</label><input class="form-control" name="${name}[${index}][icon]" placeholder="آیکن"></div><div class="col-md-2"><button class="btn btn-outline-danger" type="button" data-remove-row>حذف</button></div></div>`);}const remove=e.target.closest('[data-remove-row]');if(remove){remove.closest('[data-row]')?.remove();}});</script>@endpush
@endsection
