@extends('admin.layouts.app')
@section('title', 'تنظیمات سایت')
@section('content')
@php
    $socialPlatforms = config('social_platforms', []);
    $socialLinks = collect(old('social_links_items', $settings->get('site.social_links', [])))->map(function ($item, $key) {
        return is_array($item) ? $item : ['title' => $key, 'url' => $item, 'icon' => '', 'platform' => 'custom'];
    })->values();
@endphp
<div class="admin-page-toolbar"><div><p class="admin-eyebrow">تنظیمات</p><h2>تنظیمات عمومی سایت</h2></div></div>
<form class="admin-panel-card admin-form" action="{{ route('admin.settings.update') }}" method="POST" enctype="multipart/form-data">@csrf @method('PUT')
<div class="row g-3">
<div class="col-md-6"><label class="form-label">عنوان سایت</label><input class="form-control" name="site_title" value="{{ old('site_title', $settings->get('site.site_title', 'اتاق اصناف مرکز استان گلستان')) }}"></div>
<div class="col-md-6"><label class="form-label">عنوان متای پیش‌فرض</label><input class="form-control" name="default_meta_title" value="{{ old('default_meta_title', $settings->get('site.default_meta_title')) }}"></div>
<div class="col-12"><label class="form-label">توضیح سایت</label><textarea class="form-control js-rich-editor" name="site_description" rows="3">{{ old('site_description', $settings->get('site.site_description')) }}</textarea></div>
<div class="col-12"><label class="form-label">توضیح متای پیش‌فرض</label><textarea class="form-control" name="default_meta_description" rows="3">{{ old('default_meta_description', $settings->get('site.default_meta_description')) }}</textarea></div>
<div class="col-md-6"><label class="form-label">لوگو</label><input class="form-control" type="file" name="site_logo" accept="image/*">@if($settings->get('site.site_logo'))<small><a href="{{ Storage::url($settings->get('site.site_logo')) }}" target="_blank">مشاهده فعلی</a></small>@endif</div>
<div class="col-md-6"><label class="form-label">فاوآیکن</label><input class="form-control" type="file" name="site_favicon" accept="image/*">@if($settings->get('site.site_favicon'))<small><a href="{{ Storage::url($settings->get('site.site_favicon')) }}" target="_blank">مشاهده فعلی</a></small>@endif</div>
<div class="col-md-4"><label class="form-label">تلفن</label><input class="form-control" name="phone" value="{{ old('phone', $settings->get('site.phone')) }}"></div>
<div class="col-md-4"><label class="form-label">موبایل</label><input class="form-control" name="mobile" value="{{ old('mobile', $settings->get('site.mobile')) }}"></div>
<div class="col-md-4"><label class="form-label">ایمیل</label><input class="form-control" name="email" value="{{ old('email', $settings->get('site.email')) }}" dir="ltr"></div>
<div class="col-12"><label class="form-label">آدرس</label><textarea class="form-control" name="address" rows="2">{{ old('address', $settings->get('site.address')) }}</textarea></div>
<div class="col-12"><label class="form-label">لینک نقشه</label><input class="form-control" name="map_url" value="{{ old('map_url', $settings->get('site.map_url')) }}" dir="ltr"></div>
<div class="col-12"><label class="form-label">شبکه‌های اجتماعی</label><div data-social-list="social_links_items" data-platforms='@json($socialPlatforms)' data-next-index="{{ $socialLinks->count() }}"><div data-rows>@foreach($socialLinks as $index => $social)<div class="row g-2 align-items-end mb-2" data-row><div class="col-md-2"><label class="form-label">شبکه</label><select class="form-control" name="social_links_items[{{ $index }}][platform]">@foreach($socialPlatforms as $value => $platform)<option value="{{ $value }}" @selected(($social['platform'] ?? 'custom') === $value)>{{ $platform['icon'] }} {{ $platform['title'] }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">عنوان</label><input class="form-control" name="social_links_items[{{ $index }}][title]" placeholder="عنوان" value="{{ $social['title'] ?? '' }}"></div><div class="col-md-4"><label class="form-label">لینک</label><input class="form-control" name="social_links_items[{{ $index }}][url]" placeholder="لینک" dir="ltr" value="{{ $social['url'] ?? '' }}"></div><div class="col-md-2"><label class="form-label">آیکن</label><input class="form-control" name="social_links_items[{{ $index }}][icon]" placeholder="آیکن" value="{{ $social['icon'] ?? '' }}"></div><div class="col-md-2"><button class="btn btn-outline-danger" type="button" data-remove-row>حذف</button></div></div>@endforeach</div><button class="btn btn-outline-primary" type="button" data-add-social>افزودن شبکه اجتماعی</button></div></div>
</div><div class="mt-3"><button class="admin-primary-btn">ذخیره تنظیمات</button></div></form>
@push('scripts')<script>document.addEventListener('click',function(e){const add=e.target.closest('[data-add-social]');if(add){const list=add.closest('[data-social-list]'),rows=list.querySelector('[data-rows]'),name=list.dataset.socialList,index=Number(list.dataset.nextIndex||0),platforms=JSON.parse(list.dataset.platforms||'{}');list.dataset.nextIndex=index+1;const options=Object.entries(platforms).map(([value,item])=>`<option value="${value}">${item.icon||''} ${item.title||value}</option>`).join('');rows.insertAdjacentHTML('beforeend',`<div class="row g-2 align-items-end mb-2" data-row><div class="col-md-2"><label class="form-label">شبکه</label><select class="form-control" name="${name}[${index}][platform]">${options}</select></div><div class="col-md-2"><label class="form-label">عنوان</label><input class="form-control" name="${name}[${index}][title]" placeholder="عنوان"></div><div class="col-md-4"><label class="form-label">لینک</label><input class="form-control" name="${name}[${index}][url]" placeholder="لینک" dir="ltr"></div><div class="col-md-2"><label class="form-label">آیکن</label><input class="form-control" name="${name}[${index}][icon]" placeholder="آیکن"></div><div class="col-md-2"><button class="btn btn-outline-danger" type="button" data-remove-row>حذف</button></div></div>`);}const remove=e.target.closest('[data-remove-row]');if(remove){remove.closest('[data-row]')?.remove();}});</script>@endpush
@endsection
